[package]
name = "cuda_builder"
version = "0.3.0"
edition = "2024"
authors = ["Riccardo D'Ambrosio <rdambrosio016@gmail.com>", "The rust-gpu Authors"]
license = "MIT OR Apache-2.0"
description = "Builder for easily building rustc_codegen_nvvm crates"
repository = "https://github.com/Rust-GPU/rust-cuda"
readme = "../../README.md"

[package.metadata.docs.rs]
no-default-features = true

[features]
default = ["rustc_codegen_nvvm"]
# Cargo builds and identifies the exact backend dependency via an internal macro.
# Disable default features when exclusively using CudaBuilder::with_backend.
rustc_codegen_nvvm = ["dep:cuda_builder_backend"]
llvm21 = ["nvvm/llvm21", "cuda_builder_backend?/llvm21"]

[dependencies]
cuda_builder_backend = { path = "../cuda_builder_backend", version = "0.1", optional = true }
nvvm = { path = "../nvvm", version = "0.1" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
